### ISSUE TITLE
Security support - permissions for screens, components, menu items

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#16]
It should be possible to:

- [ ] hide menu items
- [ ] show error message about insufficient privileges when opening CRUD screens
- [ ] show visual components based on permissions for linked attribute:
  - access to the attribute is restricted - component is not displayed
  - attribute is read-only - component is in read-only mode

#### Test coverage requirements

Spec requires a total of at least 15 tests.
