### ISSUE TITLE
Visual components library

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#25]
### General Requirements

- Provide a set of visual React components similar to the CUBA platform UI components, with a mechanism for binding to data sources.
- Provide means to completely replace the standard library of components with a different one.

### Components List

- Containers
  - [x] **Grid** - a configurable grid that allows you to define a responsive (changeable depending on the screen resolution) layout of components without the need for CSS. #691
  **AppLayout** - a set of typical components of the main application framework:
    - [x] **Header** #692
    - [x] **Footer** #692
    - [x] **Sidebar** #692
  - [x] **TabSheet** - container with switchable tabs. #693
  - [x] **Card** - a highlighted block that displays a grouped set of data and / or controls. #694
- Displaying data
  - [x] **Label** - displays text. #695
  - [x] **Table** - a table for displaying data. Being bound to a data source, it allows sorting, filtering, highlighting one or more rows. Has a filtering interface built into the header for each column corresponding to an attribute of the entity of the data model. #718
  - [x] **Tree** - displays data in the form of a tree. Provides the ability to collapse / expand nodes to navigate the path of interest. #696
  - [x] **Calendar** - calendar grid (by months) with the ability to display events by day. #697
  - [x] **Image** - display a picture. #698
  - [x] **ProgressBar** - visualization of task progress. #699
  - [x] **Tooltip** #700
- Controls and data entry
  - [x] **TextField** - text field for displaying / entering data. #701
  - [x] **TextArea** - text field for displaying / entering multi-line data. Size can be adjusted. #702
  - [x] **DateField** / **TimeField** - fields for displaying and entering date and time. Provides a visual calendar for date pickers. Supports custom date and time formats. #704 #703
  - [x] **Select** - selection of one or several items from the drop-down list. Allows you to type from the keyboard by filtering the available data (including requesting from the server). #705
  - [x] **Dropdown** - drop-down list of values. #812
  - [x] **CheckBox** - a component displaying a logical on / off state. #706
  - [x] **RadioButton** - a component that switches the selection of one value from the list in a group of the same components. #707
  - [x] **Button** #708
  - [x] **Slider** - displays and selects a range of values ​​using draggable sliders. #709
  - [x] **ColorPicker** #710
  - [x] **FileUpload** - upload files. Optional - displaying the name and link to the uploaded file. #712
  - [x] **MaskedField** - a text field that allows you to restrict the input data according to the specified format. #713
  - [x] **Pagination** - page-by-page navigation through the list of data. #711
  - [x] **SourceCodeEditor** - highlighted program code editor. #714
  - [x] **RichTextArea** - visual text editor. #715
- Complex components
  - [x] **Form** - a group of fields and controls, usually associated with a data source. #636
  - [x] **Filter** - a composite component that allows you to set the conditions for filtering the loaded data. As a rule, it works in conjunction with a data source. #637
  - [x] **EntityPicker** - allows selecting an entity instance Typically associated with a referenced attribute of a data source entity. #635
- [x] **Icons** - typical set of symbols used in the user interface. #717

### Test Coverage

Each component is covered by e2e tests

**Comment by owlet1997** [comment]
all epic issues had been closed
